MVCControlReclamos/Controllers/ReclamoController.cs
using BusinessLogic.Controllers;
using Common.Constantes;
using Common.DTOs;
using DataAccess.Model;
using MVCControlReclamos.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace MVCControlReclamos.Controllers
{
    [UserAuthentication]
    public class ReclamoController : Controller
    {

        public ActionResult ListarReclamos()
        {
            BLReclamoController BLreclamo = new BLReclamoController();
            List<DtoReclamo> colReclamos = BLreclamo.reclamosCronologicamente();
            ViewBag.CantPorPag = 10;
            ViewBag.PagActual = 1;
            ViewBag.BtnTarget = "btnRec";
            ViewBag.Target = "target";
            ViewBag.ColReclamosVar = "null";
            ViewBag.Atrazado = false;
            ViewBag.AtrazadoStr = "false";
            BLTipoDeReclamoController BLT = new BLTipoDeReclamoController();
            BLZonaController BLZ = new BLZonaController();
            BLCuadrillaController BLC = new BLCuadrillaController();
            List<SelectListItem> listaTipo = new List<SelectListItem>();
            List<SelectListItem> listaZona = new List<SelectListItem>();
            List<SelectListItem> listaCuadrilla = new List<SelectListItem>();
            List<SelectListItem> listaEstado = new List<SelectListItem>();
            List<DtoTipoReclamo> colTipos = BLT.getTiposDeReclamos();
            List<DtoZona> colZonas = BLZ.listarZonas();
            List<DtoCuadrilla> colCuadrillas = BLC.getColCuadrilla();
            

            foreach(DtoTipoReclamo item in colTipos)
            {
                SelectListItem opcion = new SelectListItem();
                opcion.Value = item.numero.ToString();
                opcion.Text = item.nombre;
                listaTipo.Add(opcion);
            }

            foreach (DtoZona item in colZonas)
            {
                SelectListItem opcion = new SelectListItem();
                opcion.Value = item.numero.ToString();
                opcion.Text = item.nombre;
                listaZona.Add(opcion);
            }

            foreach (DtoCuadrilla item in colCuadrillas)
            {
                SelectListItem opcion = new SelectListItem();
                opcion.Value = item.numero.ToString();
                opcion.Text = item.nombre;
                listaCuadrilla.Add(opcion);
            }
            List<String> test = new List<String>();
            foreach (estadoReclamo estado in Enum.GetValues(typeof(estadoReclamo)))
            {
                SelectListItem opcion = new SelectListItem();
                opcion.Value = estado.ToString();
                opcion.Text = enumATexto(estado);
                listaEstado.Add(opcion);
            }

            ViewBag.ListaTipos = listaTipo;
            ViewBag.ListaZonas = listaZona;
            ViewBag.ListaCuadrillas = listaCuadrilla;
            ViewBag.ListaEstados = listaEstado;

            return View(colReclamos);
        }
   
        public string enumATexto(estadoReclamo estadoEn)
        {
            string estado = estadoEn.ToString();
            string arreglado = "";

            StringBuilder sb = new StringBuilder(estado);
            

            for (int i = 0; i<estado.Length;i++)
            {
                if (i > 0)
                {
                    if (estado[i].Equals('_'))
                    {
                        arreglado += " ";
                    }
                    else if (estado[i - 1].Equals('_') && i > 0)
                    {
                        arreglado += char.ToUpper(estado[i]).ToString();
                    }
                    else
                    {
                        arreglado += char.ToLower(estado[i]).ToString();
                    }
                }
                else
                {
                    arreglado += estado[i].ToString();
                }

            }

            return arreglado;
        }
        public ActionResult Agregar()
        {
            BLTipoDeReclamoController BLTipoReclamo = new BLTipoDeReclamoController();
           

            List<SelectListItem> colTiposReclamos = new List<SelectListItem>();
            List<DtoTipoReclamo> colDtoTipos = BLTipoReclamo.getTiposDeReclamos();

            foreach (DtoTipoReclamo item in colDtoTipos)
            {
                SelectListItem option = new SelectListItem();
                option.Value = item.numero.ToString();
                option.Text = item.nombre;
                colTiposReclamos.Add(option);
            }
            ViewBag.listaDeTipos = colTiposReclamos;
            return View();
        }

        [HttpPost]
        public ActionResult AgregarReclamo(DtoReclamo dtoReclamo)
        {
            BLReclamoController BLreclamo = new BLReclamoController();
            
            dtoReclamo.fechaIngreso = DateTime.Now;
            BLreclamo.agregarReclamo(dtoReclamo);
            return RedirectToAction("ListarReclamos");
        }

        [HttpPost]
        public ActionResult EditarReclamo (DtoReclamo dto)
        {
            string username = (string)Session[CLogin.KEY_SESSION_USERNAME];

            BLReclamoController reclamoController = new BLReclamoController();
            List<string> colErrores = reclamoController.modificarReclamo(dto, username);
           

            foreach (string error in colErrores)
            {
                ModelState.AddModelError("ErrorGeneral", error);
            }

           
            return RedirectToAction("ListarReclamos");

        }

        public ActionResult IrEditar(int nroReclamo)
        {
            BLReclamoController reclamoController = new BLReclamoController();
            DtoReclamo reclamo = reclamoController.GetById(nroReclamo);


            List<SelectListItem> colEstadoReclamos = new List<SelectListItem>();

            foreach (estadoReclamo estado in Enum.GetValues(typeof(estadoReclamo)))
            {
                SelectListItem opcion = new SelectListItem();
                opcion.Value = estado.ToString();
                opcion.Text = enumATexto(estado);
                colEstadoReclamos.Add(opcion);
            }
            ViewBag.listaDeEstados = colEstadoReclamos;
            return View("EditarReclamo",reclamo);
        }

        [HttpGet]
        public JsonResult Atrazados()
        {
            BLReclamoController BLR = new BLReclamoController();
            List<DtoReclamo> sinResolver=BLR.reclamosSinTerminar();
            foreach (DtoReclamo item in sinResolver)
            {
                item.fechaString = item.fechaIngreso.ToString();
            }
            sinResolver = sinResolver.OrderByDescending(r => r.fechaIngreso).Reverse().ToList();
    

            return Json(sinResolver, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public ActionResult mostrarReclamos(DtoFiltroReclamo filtro)
        {
            BLReclamoController BLR = new BLReclamoController();
            List<DtoReclamo> colreclamos = new List<DtoReclamo>();
            DateTime? ini;
            DateTime inicio;
            string targetID=filtro.targetID;
            int pagActual=filtro.paginaActual;
            int cantPorPag = filtro.cantPorPag;
            int? numZona;
            int? numCuadrilla;
            string estado;
            int? numTipo = filtro.tipo;
            

            if (filtro.colReclamos[0]==null)
            {

                ini = filtro.ini;
                if(ini!=null)
                {
                    inicio = (DateTime)ini;
                }
                else
                {
                    inicio = DateTime.MinValue;
                }

                numZona = filtro.numZona;
                numCuadrilla = filtro.numCuadrilla;
                estado = filtro.estado;
                ViewBag.ColReclamosVar = "null";

                colreclamos = BLR.getReclamos(numZona, numCuadrilla, estado, ini, null);
                
                if (ini != null)
                {
                    colreclamos =colreclamos.Where(r=>r.fechaIngreso.Date==inicio).ToList();
                }
                if (numTipo != null)
                {
                    colreclamos = colreclamos.Where(r => r.numTipoReclamo == numTipo).ToList();
                }
                if (numZona != null)
                {
                    colreclamos = colreclamos.Where(r => r.numeroZona == numZona).ToList();
                }
                if (estado != null)
                {
                    colreclamos = colreclamos.Where(r => r.estado.ToString()==estado).ToList();
                }
                colreclamos=colreclamos.OrderByDescending(r=>r.fechaIngreso).ToList();

            }
            else
            {
                colreclamos = filtro.colReclamos;
                ViewBag.ColReclamosVar = filtro.colRelJavVar;
            }
            ViewBag.AtrazadoStr = filtro.atrazado.ToString().ToLower();
            ViewBag.Atrazado = filtro.atrazado;
            ViewBag.CantPorPag = filtro.cantPorPag;
            ViewBag.BtnTarget = filtro.BtnTarget;   
            ViewBag.ColReclamos = filtro.colReclamos;
            ViewBag.TotReclamos = colreclamos.Count();
            ViewBag.PagActual = pagActual;
            ViewBag.Target = targetID;

            colreclamos = colreclamos.Skip(cantPorPag * (pagActual - 1)).Take(cantPorPag).ToList();
            return PartialView("_ListarReclamosPartial", colreclamos);
        }

        public ActionResult Detalle(int numReclamo)
        {
            BLReclamoController BLR = new BLReclamoController();
            BLCuadrillaController BLC = new BLCuadrillaController();
            BLZonaController BLZ = new BLZonaController();
            DtoReclamo reclamo = BLR.GetById(numReclamo);
            DtoCuadrilla cuadrilla = BLC.getCuadrilla(reclamo.numeroCuadrilla);

MVCControlReclamos/Controllers/TipoReclamoController.cs
using BusinessLogic.Controllers;
using Common.DTOs;
using MVCControlReclamos.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCControlReclamos.Controllers
{
    [UserAuthentication]
    public class TipoReclamoController : Controller
    {

        public ActionResult ListarReclamos()
        {
            BLTipoDeReclamoController BLTdR = new BLTipoDeReclamoController();
            List<DtoTipoReclamo> colTipoReclamo = BLTdR.getTiposDeReclamos();
            return View(colTipoReclamo);
        }

        public ActionResult Agregar()
        {
            return View();
        }
        public ActionResult AgregarTipoReclamo(DtoTipoReclamo dtoTipoReclamo)
        {
            BLTipoDeReclamoController BLTdR = new BLTipoDeReclamoController();
            BLTdR.agregarTipoReclamo(dtoTipoReclamo);

            return RedirectToAction("ListarReclamos");
        }
    }
}

MVCControlReclamos/Controllers/UsuarioController.cs
using BusinessLogic.Controllers;
using Common.DTOs;
using MVCControlReclamos.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCControlReclamos.Controllers
{
    [UserAuthentication]
    public class UsuarioController : Controller
    {
       
        public ActionResult AgregarUsuario()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AgregarUsuario(DtoUsuario dtoUsuario)
        {
            BLUsuarioController BLUsuario = new BLUsuarioController();
            dtoUsuario.funcionario = true;
            BLUsuario.altaUsuario(dtoUsuario);
            return RedirectToAction("AgregarUsuario");
        }

        public JsonResult ValidarUsuario(string usario)
        {
            bool rest = true;
            BLUsuarioController usuarioController = new BLUsuarioController();
            if (usuarioController.ExisteNombreUsuario(usario) == true)
            {
                rest = false;
            }
            return Json(rest, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ValidarEmail(string email)
        {
            bool rest = true;
            BLUsuarioController usuarioController = new BLUsuarioController();
            if (usuarioController.ExisteEmail(email) == true)
            {
                rest = false;
            }
            return Json(rest, JsonRequestBehavior.AllowGet);
        }

        /* public ActionResult ListarUsuarios()
         {
             BLUsuarioController BLUsuario = new BLUsuarioController();
             List<DtoUsuario> colUsuarios = BLUsuario.l();
             return View(colUsuarios);
         }*/


        // /Usuario/AgregarUsuario

    }
}

MVCControlReclamos/Controllers/ZonaController.cs
using System;
using BusinessLogic.Controllers;
using Common.DTOs;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using MVCControlReclamos.Helpers;

namespace MVCControlReclamos.Controllers
{
    [UserAuthentication]
    public class ZonaController : Controller
    {
        // GET: Zona
        public ActionResult Zonas()
        {
            BLZonaController BLZ = new BLZonaController();
            List<DtoZona> colZonas = BLZ.listarZonas();
            ViewBag.ColZonas = colZonas;
            return View(colZonas);
        }

         public ActionResult NuevaZona()
        {
            BLZonaController BLZ = new BLZonaController();
            List<DtoZona> colZonas = BLZ.listarZonas();
            //ViewBag.ColZonas = colZonas;
            //ViewBag.NumeroZona = colZonas.LastOrDefault().numero+1;
            return View();
        }

        
        [HttpPost]
        public ActionResult AgregarZona(DtoZona nDtoZona)
        {
            BLZonaController BLZ = new BLZonaController();
            var resultado = new JsonResult
            {
                Data = JsonConvert.DeserializeObject(nDtoZona.Puntos)
            };
            string jsonString = JsonConvert.SerializeObject(resultado);
            JObject colPuntos = JObject.Parse(jsonString);
            List<DtoPunto> puntos = colPuntos["Data"].ToObject<List<DtoPunto>>();
            int numero = 0;
            foreach(DtoPunto item in puntos)
            {
                item.numero=numero++;
                item.numeroZona = nDtoZona.numero;
            }
            nDtoZona.colDtoPunto = puntos;
            BLZ.agregarZona(nDtoZona);
            return RedirectToAction("NuevaZona");

        }



        public JsonResult ValidarPoligono(string puntos)
        {
            
            BLZonaController BLZ = new BLZonaController();
            if (BLZ.hayPuntos())
            {
                var resultado = new JsonResult()
                {
                    Data = JsonConvert.DeserializeObject(puntos)
                };
                List<DtoZona> colZonas = BLZ.listarZonas();
                string jsonString = JsonConvert.SerializeObject(resultado);
                JObject colPuntos = JObject.Parse(jsonString);
                List<DtoPunto> poligono = colPuntos["Data"].ToObject<List<DtoPunto>>();
                bool pEnZona = false;
                bool superPuesto = false;
                bool vacio = false;
                if (!(poligono.Count() == 0))
                {
                    foreach (DtoZona zona in colZonas)
                    {
                        foreach (DtoPunto punto in zona.colDtoPunto)
                        {
                            if (BLZ.puntoEnZona((double)punto.longitud, (double)punto.latitud, poligono))
                            {
                                pEnZona = true;
                            }
                        }

                        foreach (DtoPunto punto in poligono)
                        {
                            if (BLZ.puntoEnZona((double)punto.longitud, (double)punto.latitud, zona.colDtoPunto))
                            {
                                pEnZona = true;
                            }
                        }
                    }
                    superPuesto = BLZ.zonaSuperPuesta(poligono, colZonas);
                }
                else
                {
                    vacio = true;
                }


                if (poligono.Count() < 3 || vacio)
                {
                    return Json("• La zona requiere de al menos 3 puntos", JsonRequestBehavior.AllowGet);
                }
                else if (pEnZona || superPuesto)
                {
                    return Json("• La zona no puede superponerse a otra", JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(true, JsonRequestBehavior.AllowGet);
                }
               
            }
            else { return Json(true, JsonRequestBehavior.AllowGet); }
        }

        [HttpGet]
        public ActionResult cargarZonasBD()
        {
            BLZonaController BLZ = new BLZonaController();
            List<DtoZona> colZonas = BLZ.listarZonas();
            ViewBag.ColZonas = colZonas;
            return Json(colZonas,JsonRequestBehavior.AllowGet);

        }



        public ActionResult Preuba()
        {
            return View();
        }
    }
}

MVCControlReclamos/Views/Shared/_DetalleReclamo.cshtml
@model Common.DTOs.DtoReclamo

<div class="">
    @{
        string estado;
        if (Model.estado == Common.DTOs.estadoReclamo.ASIGNADO)
        {
            estado = "primary";
        }
        else if (Model.estado == Common.DTOs.estadoReclamo.EN_PROCESO)
        {
            estado = "warning";
        }
        else if (Model.estado == Common.DTOs.estadoReclamo.DESESTIMADO)
        {
            estado = "secondary";
        }
        else if (Model.estado == Common.DTOs.estadoReclamo.RESUELTO)
        {
            estado = "success";
        }
        else
        {
            estado = "danger";
        }
    }
    <div class="row">

        <div class="col-lg-6 ">
            <dl id="dlDetRec">

                <dd>
                    @Html.ActionLink("Editar Estado", "IrEditar", new { nroReclamo = Model.numero }, new { @class = "btn btn-m btn-info" })
                    @Html.ActionLink("Ver Historial", "../HistorialCambios/ListarHistorialCambios", new { nroReclamo = Model.numero }, new { @class = "btn btn-m btn-info" })
                </dd>

                <dt>
                    Numero:
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.numero)
                </dd>

                <dt>
                    Fecha ingresado:
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.fechaIngreso)
                </dd>

                <dt>
                    Observaciones:
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.observaciones)
                </dd>

                <dt>
                    Tipo de Reclamo:
                </dt>

                <dd>
                    @ViewBag.TipoReclamo
                </dd>

                <dt>
                    Usuario:
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.emailUsuario)
                </dd>

                <dt>
                    Cuadrilla:
                </dt>

                <dd>
                    @ViewBag.Cuadrilla
                </dd>

                <dt>
                    Zona:
                </dt>

                <dd>
                    @ViewBag.Zona
                </dd>
                <dt>
                    Comentrios:
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.comentario)
                </dd>
                <dd class="col-lg-12">

                </dd>
            </dl>

        </div>
        <div class="col-lg-6" id="asignadoDetalle">
            <dl>
                <dt class="text-center">

                    Estado:   <label class="label label-@estado">@ViewBag.Estado</label>

                </dt>

                <dd class="text-center ">
                </dd>


            </dl>

        </div>
    </div>
</div>

@{ try
    {

        string lat = Model.latitud.ToString();
        string lng = Model.longitud.ToString();
        string latPutno = "";
        string lngPunto = "";

        foreach (char letra in lat)
        {
            if (letra.Equals(','))
            {
                latPutno += ".";
            }
            else { latPutno += letra; }

        }
        foreach (char letra in lng)
        {
            if (letra.Equals(','))
            {
                lngPunto += ".";
            }
            else { lngPunto += letra; }

        }

        <input type="number" class="hidden" id="numZona" value="@ViewBag.Zona.numero" readonly="readonly" />
        <label id="lat" class="hidden">@latPutno</label>
        <label id="lng" class="hidden">@lngPunto</label>
    }
    catch { }


}




@Styles.Render("~/Content/estilos")

MVCControlReclamos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Alcaldía de Toledo</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Tipos Reclamo", "ListarReclamos", "TipoReclamo")</li>
                    <li>@Html.ActionLink("Reclamos", "ListarReclamos", "Reclamo")</li>
                    <li>@Html.ActionLink("Cuadrillas", "ListarCuadrillas", "Cuadrilla")</li>
                    <li>@Html.ActionLink("Zonas", "Zonas", "Zona")</li>
                    @{ try
                        {
                            if (@Session.Keys.Count > 0)
                            {
                                <li>@Html.ActionLink("Log Out", "LogOut", "Login")</li>
                            }
                            else
                            {
                                <li>@Html.ActionLink("Log In", "LogIn", "Login")</li>
                                <li>@Html.ActionLink("Registrarse", "AgregarUsuario", "Usuario")</li>
                            }
                        }
                        catch { }
                    }
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Alcaldía de toledo</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Styles.Render("~/Content/estilos")
    @RenderSection("scripts", required: false)
</body>
</html>

MVCControlReclamos/Views/Shared/_ListarReclamosPartial.cshtml
@model IEnumerable<Common.DTOs.DtoReclamo>
@Styles.Render("~/Content/estilos")
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.numero)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tipoReclamo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.emailUsuario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fechaIngreso)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.estado)
        </th>

        <th></th>
    </tr>

    @{
        List<Common.DTOs.DtoReclamo> colReclamos = Model.ToList();
        int totalReclamos;
        int CantPorPag;
        int paginaActual;
        if (ViewBag.PagActual != null)
        {
            paginaActual = ViewBag.PagActual;
        }
        else
        {
            paginaActual = 1;
        }
        if (ViewBag.TotReclamos != null)
        {
            totalReclamos = ViewBag.TotReclamos;
        }
        else
        {
            totalReclamos = Model.Count();
        }
        if (ViewBag.CantPorPag != null)
        {
            CantPorPag = ViewBag.CantPorPag;
        }
        else
        {
            CantPorPag = 10;
        }

        int totalPaginas = (totalReclamos / CantPorPag);
        float paginas = ((float)totalReclamos /(float) CantPorPag);

        if (!(paginas % 2 == 0))
        {
            totalPaginas += 1;
        }

        colReclamos = colReclamos.Take(CantPorPag).ToList();
        List<string> siguiente = new List<string>() { "", "" };
        List<string> anterior = new List<string>() { "", "" };
    }
    @foreach (var item in colReclamos)
    {
        string estado;
        if (item.estado == Common.DTOs.estadoReclamo.ASIGNADO)
        {
            estado = "primary";
        }
        else if (item.estado == Common.DTOs.estadoReclamo.EN_PROCESO)
        {
            estado = "warning";
        }
        else if (item.estado == Common.DTOs.estadoReclamo.DESESTIMADO)
        {
            estado = "secondary";
        }
        else if (item.estado == Common.DTOs.estadoReclamo.RESUELTO)
        {
            estado = "success";
        }
        else
        {
            estado = "danger";
        }

        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.numero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tipoReclamo.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.emailUsuario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fechaIngreso)
            </td>
            <td>
                <label class="label label-@estado"> @item.estado</label>
            </td>
            <td>
                @Html.ActionLink("Detalles", "DetallesReclamo", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
    }
</table>
<div class="row bb">
    <div class="row">

        <dib class="text-right col-xs-4">
          
        </dib>
        <div class="col-xs-4 ">
            <div class="row ">
                <div class="text-right col-xs-4  ">
                    @if (paginaActual > 1)
                    {
                        <input id="@ViewBag.BtnTarget" type="button" value="Anterior" class="btn-xs btn-info btn" onclick='cargarReclamos(@ViewBag.ColReclamosVar, "@ViewBag.Target", @paginaActual-1,@CantPorPag,"@ViewBag.BtnTarget","@ViewBag.ColReclamosVar")' />
                    }
                </div>
                <div class="col-xs-4 "><label>@paginaActual de @totalPaginas</label></div>
                <div class="text-left col-xs-4">
                    @if (paginaActual < totalPaginas)
                    {
                        <input id="@ViewBag.BtnTarget" type="button" value="Siguiente" class="btn-xs btn-info btn" onclick='cargarReclamos(@ViewBag.ColReclamosVar, "@ViewBag.Target", @paginaActual+1,@CantPorPag,"@ViewBag.BtnTarget","@ViewBag.ColReclamosVar","","","","","","","",false)' />
                    }
                </div>
                
            </div>
        </div>
        <dib class="text-left col-xs-4">
           
            </dib>

    </div>
</div>

<script src="~/Scripts/JS.js"></script>

MVCControlReclamos/Views/Shared/_ListarZonas.cshtml
@model IEnumerable<Common.DTOs.DtoZona>

<div class="panel-group" id="accordion">

    @foreach (var item in Model)
    {
        ViewBag.ColReclamosVar = "colRecJava_" + item.numero;
        ViewBag.Target = "zona_" + item.numero;
        ViewBag.BtnTarget = "btnZona_" + item.numero;
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <label class="control-label col-m-2">@item.nombre</label>

                    </div>
                    <div class="col-xs-3">
                        <input data-toggle="collapse" data-parent="#accordion" href="#collapse_@item.numero" type="button" value="Ver Reclamos" class="btn btn-xs btn-info" />
                    </div>
                </div>
            </div>
            <div id="collapse_@item.numero" class="panel-collapse collapse">
                <div class="panel-body">
                    <div class="col-lg-12">
                        <div id="zona_@item.numero">
                            @Html.Partial("_ListarReclamosPartial", item.colReclamos.Where(r=>r.numeroCuadrilla==ViewBag.NumCuadrilla))
                        </div>
                    </div>
                </div>
            </div>
        </div><div class="JsScript">
    @{
        bool existe;
        if (item.colReclamos.Count() > 0)
        {
            existe = true;
        }
        else
        {
            existe = false;
        }
        var json = new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(item.colReclamos);

        string colreclamos="[";
        int contador = 1;
        foreach (var reclamo in item.colReclamos)
        {

            colreclamos = colreclamos + "{\"numero\":" + reclamo.numero + ","
                                   + "\"numCuadrilla\":" + reclamo.numeroCuadrilla + ","
                                   + "\"numZona\":" + reclamo.numeroZona + ","
                                   + "\"longitud\":" + reclamo.longitud + ","
                                   + "\"latitud\":" + reclamo.latitud + ","
                                   + "\"observaciones\":\"" + reclamo.observaciones + "\","
                                   + "\"emailUsuario\":\"" + reclamo.emailUsuario + "\",";

            colreclamos += "\"tipoReclamo\":{\"nombre\":\"" + reclamo.tipoReclamo.nombre + "\",\"numero\":" + reclamo.tipoReclamo.numero+
                           ",\"descripcion\":\"" + reclamo.tipoReclamo.descripcion+ "\"},";

            colreclamos +="\"numTipoReclamo\":" + reclamo.numTipoReclamo + ","
            + "\"fechaIngreso\":\"" + reclamo.fechaIngreso + "\","
            + "\"estado\":\"" + reclamo.estado + "\"}" ;
            if(item.colReclamos.Count()>contador)
            {
                colreclamos += ",";
            }
            else
            {
                colreclamos += "]";
            }

            contador++;



        }





    }

    <script type="text/javascript">
                      var ff = new Date ()
        var existeJava = "@existe";
        var colRecJava_@item.numero = @Html.Raw(colreclamos)


        
    </script>
</div>


    }
</div>

    @Styles.Render("~/Content/estilos")