MVCControlReclamos/Controllers/CuadrillaController.cs
using BusinessLogic.Controllers;
using Common.DTOs;
using MVCControlReclamos.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCControlReclamos.Controllers
{
    [UserAuthentication]
    public class CuadrillaController : Controller
    {
        public ActionResult ListarCuadrillas()
        {
            BLCuadrillaController BLCuadrilla = new BLCuadrillaController();
            List<DtoCuadrilla> colCuadrillas = BLCuadrilla.getColCuadrilla();

            return View(colCuadrillas);
        }

        public ActionResult Agregar()
        {
            return View();
        }

        public ActionResult AgregarCuadrilla(DtoCuadrilla dtoCuadrilla)
        {
            BLCuadrillaController BLCuadrilla = new BLCuadrillaController();
            BLCuadrilla.agregarCuadrilla(dtoCuadrilla);

            return RedirectToAction("ListarCuadrillas");
        }

        public ActionResult AsignarZona(int numero)
        {
            BLCuadrillaController BLC = new BLCuadrillaController();
            DtoAsignarZonaCuadrilla asignado = new DtoAsignarZonaCuadrilla();
            DtoCuadrilla cuadrilla = BLC.getCuadrilla(numero);
            asignado.numCuadrilla = cuadrilla.numero;
            asignado.nombreCuadrilla = cuadrilla.nombre;
            return View(asignado);
        }

        public ActionResult Asignar(DtoAsignarZonaCuadrilla asignacion)
        {
            BLCuadrillaController BLC = new BLCuadrillaController();
            BLC.asignarCuadrillaZona(asignacion);

            return RedirectToAction("ListarCuadrillas");
        }


        public ActionResult DetalleCuadrilla(int numCuadrilla)
        {
            BLCuadrillaController BLC = new BLCuadrillaController();
            DtoCuadrilla cuadilla = BLC.getCuadrilla(numCuadrilla);
            ViewBag.CantPorPag = 10;
            ViewBag.PagActual = 1;

            return View(cuadilla);
        }


    }
}

MVCControlReclamos/Views/Cuadrilla/Agregar.cshtml
@model Common.DTOs.DtoCuadrilla

@{
    ViewBag.Title = "Agregar cuadrilla";
}

<h2>Agregar</h2>


@using (Html.BeginForm("AgregarCuadrilla","Cuadrilla")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DtoCuadrilla</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.encargado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.encargado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.encargado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cantidadPeones, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cantidadPeones, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cantidadPeones, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                <input type="button" value="Cancelar" class="btn btn-default" onclick="location.href='@Url.Action("ListarCuadrillas","Cuadrilla")'" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ListarCuadrillas")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCControlReclamos/Views/Cuadrilla/AsignarZona.cshtml
@model Common.DTOs.DtoAsignarZonaCuadrilla


@using (Html.BeginForm("Asignar","Cuadrilla")) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>DtoCuadrilla</h4>
    <hr />

    @Html.Partial("_Mapa")

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label class="control-label col-md-2">Zona: </label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.nombreZona, new { htmlAttributes = new { @class = "form-control", @placeholder = "Zona", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.numeroZona, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Cuadrilla: </label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.nombreCuadrilla, new { htmlAttributes = new { @class = "form-control", @placeholder = "Cuadrilla", @readonly = "readonly" } })
        </div>
    </div>
    @Html.EditorFor(model => model.numCuadrilla, new { htmlAttributes = new { @class = "form-control", @placeholder = "numero", @style = "visibility:hidden;" } })
    @Html.EditorFor(model => model.numeroZona, new { htmlAttributes = new { @class = "form-control", @placeholder = "numero", @style = "visibility:hidden;" } })

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Asignar" class="btn btn-default" />
        </div>
    </div>
</div>
}

<script>
    administrador = true;
</script>

<div>
    @Html.ActionLink("Back to List", "ListarCuadrillas")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCControlReclamos/Views/Cuadrilla/DetalleCuadrilla.cshtml
@model Common.DTOs.DtoCuadrilla



<div>
    <h3>Detalle Cuadrilla</h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.encargado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.encargado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cantidadPeones)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cantidadPeones)
        </dd>

    </dl>
</div>
<hr />
@{
    ViewBag.NumCuadrilla = Model.numero;
}
<div id="Zonas">
    <h4>Zonas: </h4>
    @Html.Partial("_ListarZonas", Model.colDtoZona)
</div>
<hr />
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "ListarCuadrillas")
</p>

MVCControlReclamos/Views/Cuadrilla/ListarCuadrillas.cshtml
@model IEnumerable<Common.DTOs.DtoCuadrilla>

@{
    ViewBag.Title = "ListarCuadrillas";
}

<h2>ListarCuadrillas</h2>

<p>
    @Html.ActionLink("Agregar cuadrilla", "Agregar", "Cuadrilla")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.encargado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cantidadPeones)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.encargado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.cantidadPeones)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Detalles", "DetalleCuadrilla", new {  numCuadrilla=item.numero  }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Asignar Zona", "AsignarZona", new { numero=item.numero })
        </td>
    </tr>
}

</table>